extends Node

# Procedurally builds several new built-in arenas for Local (bot) play, each
# saved as its own .tscn under game/levels/local_maps/ -- same node shape
# tag_arena.tscn uses (a "Tiles" TileMapLayer in group "arena_tiles", a
# "SpawnPoints" Node2D of Marker2D children, a "Waypoints" Node2D of
# Marker2D children in group "ai_waypoint") so game.gd's existing
# SpawnPoints/ai_waypoint lookups work unmodified regardless of which map
# got picked. Run via:
#   godot --headless --path . res://tools/generate_local_maps.tscn
#
# Waypoints don't need hand-wired edges -- ai/waypoint_graph.gd auto-
# connects any two within MAX_EDGE_DISTANCE that have clear line of sight
# through the arena's real collision geometry, so one marker per platform
# (or every ~300px along a wide one) is enough for NPCs to path the whole
# map correctly.

const TILE_SIZE := 10
const OUT_DIR := "res://levels/local_maps"
const TILESET := preload("res://levels/tag_tileset.tres")
const Catalog := preload("res://levels/local_maps/catalog.gd")

# Ground-floor platforms get spawns spread along their top surface --
# matches tag_arena's own all-spawns-on-the-floor layout. Catalog.gd's
# platform rects don't carry a "spawns" flag themselves (generation-only,
# not needed by the picker's preview icon), so it's derived here instead:
# 360 sits strictly between the highest non-floor platform's y0 (340, in
# staircase's middle steps) and the lowest actual floor's y0 (380, in
# scattered_islands) across every map in the catalog.
const SPAWN_FLOOR_Y := 360

# Every map gets sealed into a solid box (left wall, right wall, ceiling --
# the ground floor already closes the bottom) so wall-jump/wall-tech works
# at the map's edges instead of players sailing off into open space. Same
# solid tile collision every platform already uses -- player.gd's wall-jump
# detection (is_on_wall_only()/get_wall_normal()) just needs real geometry
# to push against, no special tagging.
const WALL_THICKNESS := 20
# Vertical clearance above the tallest platform in a map, so the ceiling
# doesn't clip jump arcs right above the highest usable platform.
const CEILING_CLEARANCE := 300

func _ready() -> void:
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(OUT_DIR))
	for id in Catalog.MAP_ORDER:
		var def: Dictionary = Catalog.MAPS[id]
		if not def.has("platforms"):
			continue # classic_arena -- hand-built, not generated by this tool
		_build_map(id, def)
	print("GENERATE_MAPS_DONE")
	get_tree().quit()

func _build_map(id: String, def: Dictionary) -> void:
	var arena := Node2D.new()
	arena.name = "Arena"

	var spawn_points := Node2D.new()
	spawn_points.name = "SpawnPoints"
	arena.add_child(spawn_points)
	spawn_points.owner = arena

	var waypoints := Node2D.new()
	waypoints.name = "Waypoints"
	arena.add_child(waypoints)
	waypoints.owner = arena

	var tiles_layer := TileMapLayer.new()
	tiles_layer.name = "Tiles"
	tiles_layer.tile_set = TILESET
	# persistent=true is required for group membership to actually survive
	# ResourceSaver.save() below -- add_to_group()'s default (false) only
	# registers the group for the current in-memory SceneTree session and
	# is silently dropped when packing/serializing, confirmed by grepping
	# a first-pass output .tscn for "ai_waypoint"/"arena_tiles" and finding
	# neither string present anywhere in the saved file.
	tiles_layer.add_to_group("arena_tiles", true)
	arena.add_child(tiles_layer)
	tiles_layer.owner = arena

	var spawn_i := 0
	var waypoint_i := 0
	for plat in def.platforms:
		var x0: int = plat.x0
		var y0: int = plat.y0
		var x1: int = plat.x1
		var y1: int = plat.y1
		_fill_tiles(tiles_layer, x0, y0, x1, y1)
		_add_waypoints(waypoints, waypoint_i, x0, y0, x1)
		waypoint_i += 100 # keep names unique; exact numbering doesn't matter
		if y0 >= SPAWN_FLOOR_Y:
			spawn_i = _add_spawns(spawn_points, spawn_i, x0, y0, x1)

	_add_boundary_box(tiles_layer, def.platforms)

	var packed := PackedScene.new()
	packed.pack(arena)
	var out_path := "%s/%s.tscn" % [OUT_DIR, id]
	var err := ResourceSaver.save(packed, out_path)
	print("wrote map: ", id, " err=", err)

## Encloses the map's whole platform bounding box in solid walls -- left
## wall, right wall, and a ceiling, all WALL_THICKNESS thick. The ground
## floor (the lowest platform's own bottom edge) already closes the bottom,
## so no floor wall is added.
func _add_boundary_box(layer: TileMapLayer, platforms: Array) -> void:
	var min_x: float = INF
	var max_x: float = -INF
	var min_y: float = INF
	var max_y: float = -INF
	for plat in platforms:
		min_x = minf(min_x, plat.x0)
		max_x = maxf(max_x, plat.x1)
		min_y = minf(min_y, plat.y0)
		max_y = maxf(max_y, plat.y1)

	var ceiling_y: float = min_y - CEILING_CLEARANCE
	# Left/right walls span from the ceiling down to the floor's bottom so
	# they meet the ceiling with no gap in the corner.
	_fill_tiles(layer, int(min_x) - WALL_THICKNESS, int(ceiling_y), int(min_x), int(max_y))
	_fill_tiles(layer, int(max_x), int(ceiling_y), int(max_x) + WALL_THICKNESS, int(max_y))
	_fill_tiles(layer, int(min_x) - WALL_THICKNESS, int(ceiling_y) - WALL_THICKNESS, int(max_x) + WALL_THICKNESS, int(ceiling_y))

func _fill_tiles(layer: TileMapLayer, x0: int, y0: int, x1: int, y1: int) -> void:
	var gx0 := int(floor(float(x0) / TILE_SIZE))
	var gy0 := int(floor(float(y0) / TILE_SIZE))
	var gx1 := int(ceil(float(x1) / TILE_SIZE))
	var gy1 := int(ceil(float(y1) / TILE_SIZE))
	for gy in range(gy0, gy1):
		for gx in range(gx0, gx1):
			layer.set_cell(Vector2i(gx, gy), 0, Vector2i(0, 0))

## One waypoint per platform, or every ~300px along a wide one -- see the
## file header comment on why no hand-wired edges are needed.
func _add_waypoints(parent: Node2D, start_index: int, x0: int, y0: int, x1: int) -> void:
	var width := x1 - x0
	var count := maxi(1, int(round(float(width) / 300.0)))
	for i in count:
		var t := (i + 0.5) / float(count)
		var wx := x0 + t * width
		var marker := Marker2D.new()
		marker.name = "W%d" % (start_index + i)
		marker.position = Vector2(wx, y0 + 4)
		marker.add_to_group("ai_waypoint", true)
		parent.add_child(marker)
		marker.owner = parent.get_parent()

## Spreads spawn points evenly along a platform's top surface, continuing
## the running index across multiple spawn-eligible platforms in the same
## map. Returns the updated index.
func _add_spawns(parent: Node2D, start_index: int, x0: int, y0: int, x1: int) -> int:
	var width := x1 - x0
	var count := maxi(2, int(round(float(width) / 260.0)))
	for i in count:
		var t := (i + 0.5) / float(count)
		var sx := x0 + t * width
		var marker := Marker2D.new()
		marker.name = "Spawn%d" % (start_index + i)
		marker.position = Vector2(sx, y0)
		parent.add_child(marker)
		marker.owner = parent.get_parent()
	return start_index + count
