extends RefCounted
class_name LocalMapCatalog

## Single source of truth for every built-in Local (bot) map. Both the
## procedural generator (tools/generate_local_maps.gd) and local_menu.gd's
## inline map-picker row read the same `platforms` data here -- the
## generator to build the actual .tscn geometry, the picker to draw a
## matching preview icon (see ui/local_map_icon.gd) -- so a map's picker
## thumbnail can never drift out of sync with what it actually looks like
## in-game.

const CLASSIC_ID := "classic_arena"

# id -> {name, scene, platforms}. Platforms are {x0,y0,x1,y1} world-pixel
# rects, same format generate_local_maps.gd consumes directly. classic_arena
# is the original hand-built tag_arena.tscn (not generated by this tool),
# so it has no platforms entry -- local_map_icon.gd falls back to a fixed
# icon for it instead of a data-driven preview.
const MAPS := {
	"classic_arena": {
		"name": "Classic Arena",
		"scene": "res://levels/tag_arena.tscn",
	},
	"wide_open": {
		"name": "Wide Open",
		"scene": "res://levels/local_maps/wide_open.tscn",
		"platforms": [
			{"x0": -1000, "y0": 420, "x1": 1000, "y1": 480},
			{"x0": -320, "y0": 200, "x1": -100, "y1": 220},
			{"x0": 100, "y0": 200, "x1": 320, "y1": 220},
		],
	},
	"twin_towers": {
		"name": "Twin Towers",
		"scene": "res://levels/local_maps/twin_towers.tscn",
		"platforms": [
			{"x0": -1000, "y0": 420, "x1": 1000, "y1": 480},
			{"x0": -900, "y0": 0, "x1": -800, "y1": 420},
			{"x0": 800, "y0": 0, "x1": 900, "y1": 420},
			{"x0": -960, "y0": -20, "x1": -740, "y1": 0},
			{"x0": 740, "y0": -20, "x1": 960, "y1": 0},
			{"x0": -110, "y0": 150, "x1": 110, "y1": 170},
		],
	},
	"staircase": {
		"name": "Staircase",
		"scene": "res://levels/local_maps/staircase.tscn",
		"platforms": [
			{"x0": -1050, "y0": 420, "x1": -750, "y1": 500},
			{"x0": -700, "y0": 340, "x1": -450, "y1": 500},
			{"x0": -400, "y0": 260, "x1": -150, "y1": 500},
			{"x0": -100, "y0": 180, "x1": 150, "y1": 500},
			{"x0": 200, "y0": 260, "x1": 450, "y1": 500},
			{"x0": 500, "y0": 340, "x1": 750, "y1": 500},
			{"x0": 800, "y0": 420, "x1": 1050, "y1": 500},
		],
	},
	"scattered_islands": {
		"name": "Scattered Islands",
		"scene": "res://levels/local_maps/scattered_islands.tscn",
		"platforms": [
			{"x0": -1000, "y0": 380, "x1": -800, "y1": 420},
			{"x0": -650, "y0": 280, "x1": -450, "y1": 320},
			{"x0": -300, "y0": 380, "x1": -100, "y1": 420},
			{"x0": 50, "y0": 180, "x1": 250, "y1": 220},
			{"x0": 350, "y0": 380, "x1": 550, "y1": 420},
			{"x0": 650, "y0": 280, "x1": 850, "y1": 320},
			{"x0": 900, "y0": 380, "x1": 1050, "y1": 420},
			{"x0": -150, "y0": 60, "x1": 150, "y1": 100},
		],
	},
	"pillars_and_ledges": {
		"name": "Pillars & Ledges",
		"scene": "res://levels/local_maps/pillars_and_ledges.tscn",
		"platforms": [
			{"x0": -1000, "y0": 420, "x1": 1000, "y1": 480},
			{"x0": -700, "y0": 250, "x1": -650, "y1": 420},
			{"x0": -250, "y0": 300, "x1": -200, "y1": 420},
			{"x0": 200, "y0": 300, "x1": 250, "y1": 420},
			{"x0": 650, "y0": 250, "x1": 700, "y1": 420},
			{"x0": -780, "y0": 230, "x1": -600, "y1": 250},
			{"x0": 600, "y0": 230, "x1": 780, "y1": 250},
			{"x0": -320, "y0": 280, "x1": -160, "y1": 300},
			{"x0": 160, "y0": 280, "x1": 320, "y1": 300},
		],
	},
}

const MAP_ORDER := ["classic_arena", "wide_open", "twin_towers", "staircase", "scattered_islands", "pillars_and_ledges"]

## Resolves a map id to its scene path, falling back to Classic Arena for an
## unknown/missing id (deleted map, corrupt save, etc.) -- same "never
## hard-fail on missing content" rule the rest of the project follows.
static func scene_path_for(map_id: String) -> String:
	var def: Dictionary = MAPS.get(map_id, {})
	var path: String = def.get("scene", "")
	if not path.is_empty() and ResourceLoader.exists(path):
		return path
	return MAPS[CLASSIC_ID]["scene"]
